spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  datasource:
    url: ENC(o7wyn4Y/DvB1i1QR+psKUcg5zEwc1BCP0ur7vMAh8IkvhdpZt1T/yCh5xe/bSt3eKScyMxmKBd8+Krpj/wiPDUCVlHb7fe8zLqyQ0mVCbWECC7o0YS+dl5z42yoTzWXk7x/dJuXx2kl3zV/IHB/EnuT3Kyg/wvgJ1DfzJj+aV0ViVQOHDSDKHxQGPeT3W0SO)
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(zUOU4WOREW8AzOLRzMNvjg==)
    password: ENC(gcEfzZpOaUQnCQ1JJw0ew8vRl4Ejgt6S)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ENC(bsI7as07eRNwIhE4VM3P5pFpmOgkC87Q)
    username: ENC(r8uDJ2AqG8kWlhI3AAn+ng==)
    password: ENC(WR3khTFDDY/vL+WYU6QaTg==)
    port: 5672
jasypt:
  encryptor:
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES
jwt:
  secret: ENC(PI08vL6ZjPnuNwrk/be4lKuLFCIAzRaFFxEvwY4/ZyutyonU1OYoOIhKGAZb6FJwyJhScejJKjRw9E3aM+rzWynFDK4dP66rWQ8oaLpw3kITyKHQuCP5vg==)
cloud:
  aws:
    credentials:
      accessKey: ENC(wwv6CTXQkv4rt6j34SD7y4VLUP5N7b3IL62oRCUnP0I=)
      secretKey: ENC(0ZVAr2rHRw5cKUTA6aixl7/CPNXIEKPhFEhMy7VnHpC3mpXBMHX4BCLpdA84IUSORkP7FZYotMI=)
    s3:
      bucket: ENC(SdEEy3jBswZRQdCgpkB8eJZtCTT4vkfA)
    region:
      static: ENC(kox0L0aJNpuyexJ5NczEec/YrrFYVeBJ)
#    stack:
#      auto: false
server:
  port: 8080
