
jasypt:
  encryptor:
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES
jwt:
  secret: ENC(PI08vL6ZjPnuNwrk/be4lKuLFCIAzRaFFxEvwY4/ZyutyonU1OYoOIhKGAZb6FJwyJhScejJKjRw9E3aM+rzWynFDK4dP66rWQ8oaLpw3kITyKHQuCP5vg==)
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
cloud:
  aws:
    credentials:
      accessKey: ENC(wwv6CTXQkv4rt6j34SD7y4VLUP5N7b3IL62oRCUnP0I=)
      secretKey: ENC(0ZVAr2rHRw5cKUTA6aixl7/CPNXIEKPhFEhMy7VnHpC3mpXBMHX4BCLpdA84IUSORkP7FZYotMI=)
    s3:
      bucket: ENC(SdEEy3jBswZRQdCgpkB8eJZtCTT4vkfA)
    region:
      static: ENC(kox0L0aJNpuyexJ5NczEec/YrrFYVeBJ)
#    stack:
#      auto: false
server:
  port: 80
